
/* Exclui o Banco caso ele já exista
DROP SCHEMA IF EXISTS aula04;
*/
CREATE SCHEMA AULA04;
CREATE TABLE AULA04.ALUNOS
(
	 ID_ALUNO INT NOT NULL AUTO_INCREMENT
    ,NOME VARCHAR(100) NOT NULL
    ,TELEFONE VARCHAR(16) NOT NULL
    ,CONSTRAINT PK_ID_ALUNO PRIMARY KEY (ID_ALUNO)
);


